# Name of the action visible in the action overview
name: Create Percy Snapshots

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the following branches
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Snapshot capturing related work
jobs:
  create_snpashots:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Capture snapshots
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run snapshot
